-- users 테이블에 CSV 컬럼들 추가
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS program VARCHAR(200),
ADD COLUMN IF NOT EXISTS status VARCHAR(50),
ADD COLUMN IF NOT EXISTS ws_group VARCHAR(100),
ADD COLUMN IF NOT EXISTS second_term_group VARCHAR(100),
ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20),
ADD COLUMN IF NOT EXISTS attendance VARCHAR(50);

-- 기존 NOT NULL 제약조건을 완화 (CSV에 없는 컬럼들)
ALTER TABLE users 
ALTER COLUMN birth_date DROP NOT NULL,
ALTER COLUMN location DROP NOT NULL,
ALTER COLUMN mbti DROP NOT NULL; 